# Docker Engine Settings (daemon.json)
LOG_MAX_SIZE=10m
LOG_MAX_FILE=3
DEFAULT_ADDRESS_POOL_BASE=172.80.0.0/16
DEFAULT_ADDRESS_POOL_SIZE=24

# Docker Desktop Resource Limits
DD_CPUS=4
DD_MEMORY_MIB=4096
DD_SWAP_MIB=2048

# Docker Desktop Version (Build ID)
# DOCKER_DESKTOP_VERSION="196321"

# Paths
DOCKER_DESKTOP_PATH="/opt/docker-desktop/bin/docker-desktop"