# ==========================================
# Настройки репозиториев
# ==========================================

# BACKEND
# Укажите URL без протокола (например: github.com/user/backend.git или gitlab.com/user/backend.git)
BACKEND_REPO_URL="git@github.com:RomanSafonov/gm-api.git"
BACKEND_USERNAME=""
BACKEND_PASSWORD="" # Рекомендуется использовать Personal Access Token (PAT)

# FRONTEND
# Укажите URL без протокола (например: github.com/user/frontend.git)
FRONTEND_REPO_URL="git@github.com:RomanSafonov/gm-frontend.git"
FRONTEND_USERNAME=""
FRONTEND_PASSWORD=""
