# ==========================================
# Настройки конфигурации
# ==========================================

# BACKEND
BACKEND_REPO_URL="git@github.com:Zenzelya/anky.git"
BACKEND_USERNAME=""
BACKEND_PASSWORD=""

# FRONTEND
FRONTEND_REPO_URL="git@github.com:Zenzelya/anki-front.git"
FRONTEND_USERNAME=""
FRONTEND_PASSWORD=""

# ==========================================
# Создание структуры папок
# ==========================================

echo "Создание директорий проекта..."

# Создаем папки. Флаг -p предотвращает ошибки, если папки уже существуют
mkdir -p backend
mkdir -p frontend

echo "Папки backend и frontend готовы."
