services:
  gm-api:
    command: sh -c "yarn install && echo 'Start debugging...' && yarn start:dev"

  gm-frontend:
    command: sh -c "yarn install && yarn json-server --watch db.json --host 0.0.0.0 --port 3001 & yarn start"